### ISSUE TITLE
Integer OverflowError when using sha1 based hash  

### ISSUE THREAD

**Issue by ksuhail7** [renstrom/python-jump-consistent-hash#12]
When using a sha-1 based hash as key, the jump.hash() function throws an overflow error. 
Ex:

jump.hash(int(hashlib.sha1(b'abc').hexdigest(), 16), 5)

OverflowError: int too big to convert

Should the module be able to handle such keys?

**Comment by renstrom** [comment]
Thanks for report. I've uploaded v3.0.1 that should fix your issue.
